In [9]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

## Basic setup

Create anaconda environnement
<br>
```bash
conda create -n ml python=3.7.4 jupyter
```
Install fastai library
<br>
```bash
conda install -c pytorch -c fastai fastai
```

# Special types of matrices

Identity matrix $I_{n} \in \mathbb{R}^{n \times n}$ is a matrix which does not changes other matric after multiplication. This kind of matrices contain ones on main diagonal and zero everywhere else 
$$\begin{align} I_{n} &= \begin{pmatrix}
           1, 0, \dots, 0 \\
           0, 1, \dots, 0 \\
           \vdots \\
           0, 0, \dots, 1 \\
         \end{pmatrix}
  \end{align}$$
<br>
or we can define it with property $\forall a \in \mathbb{R}^{1 \times n}$ holds $aI_{n} = a$ or $\forall a \in \mathbb{R}^{n \times 1}$ holds $I_{n}a =a$

In [1]:
import numpy as np

In [2]:
I = np.identity(4)

In [3]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
A = np.random.random(size=(4, 5))
B = np.random.random(size=(6, 4))

In [5]:
A

array([[0.16608384, 0.64658418, 0.33660896, 0.55163203, 0.83862164],
       [0.5902026 , 0.72837157, 0.95135543, 0.45924322, 0.81066017],
       [0.52679628, 0.02827689, 0.84247732, 0.51773502, 0.33968376],
       [0.35130613, 0.09634971, 0.3864694 , 0.07685268, 0.26896936]])

In [6]:
B

array([[0.98289049, 0.97048821, 0.09346472, 0.4949944 ],
       [0.75362206, 0.02645528, 0.139597  , 0.69335633],
       [0.54815407, 0.81031219, 0.10572942, 0.89742611],
       [0.85674399, 0.33898318, 0.49022799, 0.51391506],
       [0.00472914, 0.72224002, 0.95829003, 0.23703028],
       [0.2340194 , 0.83559035, 0.71281628, 0.73455152]])

In [7]:
I @ A

array([[0.16608384, 0.64658418, 0.33660896, 0.55163203, 0.83862164],
       [0.5902026 , 0.72837157, 0.95135543, 0.45924322, 0.81066017],
       [0.52679628, 0.02827689, 0.84247732, 0.51773502, 0.33968376],
       [0.35130613, 0.09634971, 0.3864694 , 0.07685268, 0.26896936]])

In [8]:
B @ I

array([[0.98289049, 0.97048821, 0.09346472, 0.4949944 ],
       [0.75362206, 0.02645528, 0.139597  , 0.69335633],
       [0.54815407, 0.81031219, 0.10572942, 0.89742611],
       [0.85674399, 0.33898318, 0.49022799, 0.51391506],
       [0.00472914, 0.72224002, 0.95829003, 0.23703028],
       [0.2340194 , 0.83559035, 0.71281628, 0.73455152]])