In [ ]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

## Basic setup

Create anaconda environnement
<br>
```bash
conda create -n ml python=3.7.4 jupyter
```
Install fastai library
<br>
```bash
conda install -c pytorch -c fastai fastai
```

# Set theory basics

Set (small) collection of mathematical (unique) elements $\{x, y, z, ...\}$, for instance set of integers $\{1, 2, 3, ...\}$, set of real numbers $\mathbb{R}$ numbers. We can describe set with it's property, e.g. set of real numbers between $1$ and $5$ will be $\{x | x \in \mathbb{R}, 1\leq x \leq 5 \}$.

In [2]:
S = set([2, 4])
A = {1, 2, 3, 4, 4}
B = {2, 4}
C = {1, 2, 18, 28}
type(S), type(A), type(B), A

(set, set, set, {1, 2, 3, 4})

We say that element $a \in A$ if element $a$ belongs to set $A$ and $a \notin A$ in other case

In [3]:
1 in A, 2 in B, 3 in C

(True, True, False)

Note: sometimes we write $a, b \in A$ (or $a, b, c \in A$, $a,b,c,d \in A$, $a_1, a_2, ..., a_n \in A$) instead of $a \in A$ and $b \in A$ (or $a \in A$ and $b \in A$ and $c \in A$, $a \in A$ and $b \in A$ and $c \in A$ and $d \in A$, $a_1 \in A$ and $a_2 \in A$ and ... $a_n \in A$)

Set (category) of all "small" sets $Set$

Subset $B \subseteq A$ if for every $x$ element of $B$, $x \in A$ 

In [3]:
B.issubset(A), A.issubset(B)

(True, False)

Prove that $A \subseteq A$

# Proof #1



$$\forall a : (a \in A \Rightarrow a \in A) \Rightarrow A \subseteq A$$ 

Proper subset $B \subset A$ if for every element $b \in B$: $A \in A$ and there exists $a \in a$ such that: $a \notin B$, or in other words $B \subseteq A$ and $B \neq A$

If $A \subseteq B$ and $B \subseteq A$ $\to$ $A = B$

Empty set a $\emptyset$ is a set without elements at all and which is contained in any set $\emptyset \subseteq A$ for any $A \in Set$ so $\emptyset$ is the "smallest" set (Proof it)

In [4]:
#O = set() 
O = {}
type(O)

dict

Intersection of two sets $A$ and $B$ $A \cap B$ is a "biggest" subset of $A$ and $B$, that means for every set $C$ such that, $C \subseteq A$ and $C \subseteq B$ $\to$ (implies) $C \subseteq A\cap B$

In [ ]:
A.intersection(B), A.intersection(C)

Give an exmaples of two sets $A$ and $B$ for which $A \cap B = \emptyset$

Prove that if $B \subset A$ then $A \cap B = B$

# Proof #2

 # 1)
 
$ B \subset A  \implies A \cap B = B $
 
assume $ B \subset A$ and prove that $ A \cap B \subset B. $

$ \forall : (x \in A \cap B \implies x \in A $ and $ x \in B) \implies A \cap B \subset A $

now assume $B \subset A \cap B$

$\forall x : (x \in B \implies x \in A $ and $ x \in B)$

both inclusions give $ B = A \cap B$

# 2)
Assume $A \cap B = B $ and prove $ B \subset A$

$ \forall x : (x \in B \implies x \in A \cap B) $ (by assumtion). So $x \in A ) \implies B \subset A)$

Prove that $A \cap B = B \cap A$

# Proof #3

$ \forall x: (x \in A \cap B \implies x \in A, x \in B => x \in B \cap A) \implies A \cap B = B \cap A$




Union of two sets $A$ and $B$ $A \cup B$ is a "smallest" set that contains both - $A$ and $B$, that means:
for every set $D$ such that $A \subseteq D$ and $B \subseteq D$ $\to$ (implies) $A \cup B \subseteq D$

In [5]:
A, C, A.union(C), A.union(B) 

({1, 2, 3, 4}, {1, 2, 18, 28}, {1, 2, 3, 4, 18, 28}, {1, 2, 3, 4})

Prove that if $B \subset A$ then $A \cup B = A$

If $B \subset A \implies \forall x : (x \in B \implies x \in A) \implies x \in A \cup B$

Prove that $A \cap B = B \cap A$ that $A \cup B = B \cup A$


$\forall x : (x \in A \cap B \implies x \in A, x \in B \implies x \in A \cup B, x \in B \cup A$

Difference between two sets $A$ snd $B$ is the set $A - B$ or $A \ B$ for which $a \in A - B$ if $a \in A$ and $a \notin B$

In [ ]:
A - B, A - C, C - A, A, B, C

For set $A$ and subset $B$ we denote $A - B$ with $\overline{B}$ or $B^{C}$

Set of subsets (powerset) of the set $X$ will be $2^X = \{A | A \subseteq X\}$

In [6]:
from itertools import combinations, chain
pset = chain.from_iterable(combinations(A, r) for r in range(len(A)+1))
P_A = set(pset)
A, P_A, len(A), len(P_A), 2**(len(A)), len(P_A) == 2**(len(A))

({1, 2, 3, 4},
 {(),
  (1,),
  (1, 2),
  (1, 2, 3),
  (1, 2, 3, 4),
  (1, 2, 4),
  (1, 3),
  (1, 3, 4),
  (1, 4),
  (2,),
  (2, 3),
  (2, 3, 4),
  (2, 4),
  (3,),
  (3, 4),
  (4,)},
 4,
 16,
 16,
 True)

Cartesian product of sets $A$ and $B$ in set of ordered pairs := $A\times B = \{(a, b) | a \in A \textrm{ and } b\in B\}$

In [7]:
AxB = {(a, b) for a in A for b in B}
AxB, len(A), len(B), len(AxB)

({(1, 2), (1, 4), (2, 2), (2, 4), (3, 2), (3, 4), (4, 2), (4, 4)}, 4, 2, 8)

In [8]:
AxBxC = {(a, b, c) for a in A for b in B for c in C}
print('AxB={}'.format(AxB))
print('AxBxC={}'.format(AxBxC))

AxB={(1, 2), (3, 2), (4, 4), (1, 4), (2, 2), (4, 2), (3, 4), (2, 4)}
AxBxC={(4, 2, 2), (4, 4, 1), (1, 4, 18), (1, 2, 28), (4, 2, 18), (3, 4, 1), (1, 4, 2), (2, 4, 1), (3, 4, 2), (2, 4, 18), (4, 2, 28), (3, 2, 28), (4, 4, 28), (1, 4, 1), (3, 4, 18), (2, 4, 2), (3, 2, 2), (1, 2, 18), (3, 4, 28), (1, 4, 28), (1, 2, 1), (3, 2, 18), (2, 2, 28), (3, 2, 1), (1, 2, 2), (2, 2, 18), (2, 2, 2), (2, 2, 1), (4, 4, 18), (4, 2, 1), (2, 4, 28), (4, 4, 2)}


Exclusively for mathematicians $(a, b) = \{a, \{a, b\}\}$ and $A \times B = \{\{a, \{a, b\}\} | a \in A \textrm{ and } b\in B\}$

Every subset $R$ of $AxB$ is called relation. We write $aRb$ iff $(a, b) \in R$

Special cases of relations:

For every set $A$ the diagonal $\Delta \subseteq A \times A$ is $\{(a, a) | a \in A\}$

In [9]:
delta = {(a,b) for a in A for b in A}
print('delta={}'.format(delta))

delta={(1, 2), (3, 2), (1, 3), (4, 1), (3, 3), (3, 1), (4, 4), (2, 1), (1, 4), (2, 4), (2, 3), (4, 3), (2, 2), (4, 2), (3, 4), (1, 1)}


Equivalence relation on the set $A$: $E \subset A \times A$ with properties:
- For each $a \in A$ $aEa$, which means that diagonal $\Delta \subseteq E$ (reflexive property)
- For each $a, b \in A$ iff $aEb$ then $bEa$ (symmetric property)
- For each $a, b, c \in A$ if $aEb$ and $bEc$ then $aEc$


Partial order relation $\leq$
- For each $a \in A$ $a \leq a$, which means that diagonal $\Delta \subseteq E$ (reflexive property)
- For each $a, b \in A$ if $a \leq b$ and $b\leq a$ then $a = b$ (anti-symmetric property)
- For each $a, b, c \in A$ if $a \leq b$ and $b \leq c$ then $a \leq c$

Function, map $f$ between two sets $A$ and $B$ is the special relation such thet for every $a\in A$ and every $b^{'}, b^{''} \in B$ if $af{b^{'}}$ and $af{b^{''}}$ $\to$ $b^{'}={b^{''}}$.


We write : $f:A \to B$ or $A \xrightarrow{f} B$ instead of $f \subseteq A \times B $ and $f(a)=b$ or $f:a \mapsto b$ instead of $afb$

We write $f, g :A \to B$ or $f_1, f_2, ..., f_n : A \to B$ instead of $f: A\to B$ and $g:A \to B$ or  $f_1: A \to B$ and $f_2 : A \to B$ ... $f_n : A \to B$

In [ ]:
f = lambda x: x**2
A, set(map(f, A))

Composition of $f:A \to B$ and $g:B \to C$ is $g \circ f : A \to C$ where $a \mapsto g(f(a))$ for each $a \in A$

or $A \xrightarrow{f} B \xrightarrow{g} C$ than $g \circ f:A \to C$

Identity map $1_A:A \to A$ is defined as $1_A(a) = a$ for each $a \ int A$
<br>
If set is given we sometimes write $1:A \to A$ for simplicity

In [ ]:
g = lambda y: y + 12
gf = lambda x : g(f(x))
A, set(map(g, set(map(f, A)))), set(map(gf, A))

Injection (monomorphism): $m:A \to B$ is called injection if for eqch pair of elements $a^{'}, a^{''} \in A$ if $f(a^{'}) = f(a^{''})$ $\to$ $a^{'} = a^{''}$.

Surjection (epimorphism): $p:A \to B$ is called injection if for eqch pair of elements $a^{'}, a^{''} \in A$ if $f(a^{'}) = f(a^{''})$ $\to$ $a^{'} = a^{''}$.

Prove that:
- for every injection $m:A \to B$ and pair of functions $f, g :C \to A$: if $m \circ f = m \circ g$ then $f = g$ and vice-versa
- for every surjection $e:A \to B$ and every pair of functions $f, g :B \to C$: if $f \circ p = g \circ p$ then $f = g$ and vice-versa

Bijection: $f: A \to B$ is called bijection if $f$ is injection and surjection simultaneously

Prooof that 
- composition of injections is injection itself
- composition of surjections is surjection itself
- composition of bijections is bijection itself
<br>
or give a counterexamples

If there exists a biujection between two sets $A$ and $B$, we call this two sets equivalent sets and write $A \equiv B$ or $A \cong B$

Proove that for each set $A$:
- $A \cong A$
- iff $B \cong A$ then $B \cong A$ for every pair of sets $A$ and $B$
- if $A \cong B$ and $B \cong C$ then $A \cong C$ for every triplet $A$, $B$ and $C$

Prooof that there exists bijection between set of natural and even numbers

Proof thet if we have the bijection between two finity sets than they have an equal number of elements

Prove that $A \times B \cong B \times A$

Suppose we have a set $I$ and $A$ and bijection $i:I \to 2^A$ than $I$ is called index set.

Let $I = \mathbb{N}$ the we have a sequence of sets $(A_1, A_2, ...)$, or if $I$ is finit then we have a finity sequence of sets

We can generalize intersections and unions for as many sets as we want


$\cap_{i\in I}A_i$ and $\cup_{i\in I}A_i$

In [62]:
sets = [{1, 7 , 4}, {1, 6,7,8,8,9}, {1, 7, 10, 21}]
union = set.union(*sets)
intersection = set.intersection(*sets)
print('sets={}'.format(sets))
print('union={}'.format(union))
print('intersection={}'.format(intersection))

sets=[{1, 4, 7}, {1, 6, 7, 8, 9}, {1, 10, 21, 7}]
union={1, 4, 6, 7, 8, 9, 10, 21}
intersection={1, 7}


We can also define cartesian product of any "number" of sets $\prod_{i \in I}{A_i}$

In [63]:
from itertools import product

prod = [p for p in product(*sets)]
print('prod={}'.format(prod))

prod=[(1, 1, 1), (1, 1, 10), (1, 1, 21), (1, 1, 7), (1, 6, 1), (1, 6, 10), (1, 6, 21), (1, 6, 7), (1, 7, 1), (1, 7, 10), (1, 7, 21), (1, 7, 7), (1, 8, 1), (1, 8, 10), (1, 8, 21), (1, 8, 7), (1, 9, 1), (1, 9, 10), (1, 9, 21), (1, 9, 7), (4, 1, 1), (4, 1, 10), (4, 1, 21), (4, 1, 7), (4, 6, 1), (4, 6, 10), (4, 6, 21), (4, 6, 7), (4, 7, 1), (4, 7, 10), (4, 7, 21), (4, 7, 7), (4, 8, 1), (4, 8, 10), (4, 8, 21), (4, 8, 7), (4, 9, 1), (4, 9, 10), (4, 9, 21), (4, 9, 7), (7, 1, 1), (7, 1, 10), (7, 1, 21), (7, 1, 7), (7, 6, 1), (7, 6, 10), (7, 6, 21), (7, 6, 7), (7, 7, 1), (7, 7, 10), (7, 7, 21), (7, 7, 7), (7, 8, 1), (7, 8, 10), (7, 8, 21), (7, 8, 7), (7, 9, 1), (7, 9, 10), (7, 9, 21), (7, 9, 7)]


- $\overline{\cap_{i\in I}A_i} = \cup_{i\in I}\overline{A_i}$
- $\overline{\cup_{i\in I}A_i} = \cap_{i\in I}\overline{A_i}$
<br>
or
<br>
- $\overline{A \cap B} = \overline{A} \cup \overline{B}$
- $\overline{A \cup B} = \overline{A} \cap \overline{B}$

Prove that:
$$A \cap (B \cup C)=(A \cap B) \cup (A\cap C)$$
$$A \cup (B \cap C)=(A \cup B) \cap (A\cup C)$$

# Proof $A \cap (B \cup C)=(A \cap B) \cup (A\cap C)$


$ \forall x: ( x \in A \cap (B \cup C) \implies x \in A, x \in B \cup C \implies x \in B$ or $x \in C $

$\implies x \in B$ or $ x \in C \implies x \in A \cap B $ or $ x \in A \cap C $

$\implies x \in (A \cap B) \cup (A \cap C)$

# Proof $A \cup (B \cap C)=(A \cup B) \cap (A\cup C)$

$\forall x: (x \in A \cup B \cap C \implies x \in A $ or $ (x \in B $ and $ x \in C) $

$ \implies x \in A \cup B$ and $ x \in A \cup C $

$ \implies x \in (A \cup B) \cap (A \cup C)$

# Linear Algebra

Branch of mathematics widle used in many feilds. We'll introduce you to the essentials used in ML and DL.
Many notions are simplified (sorry for mathematicians) for better ubderstanding and implementation.
We'll implement some basics of LA in NumPy library and have a glance of it's use in CS fields.

## Scalars

Real set of numbers $\mathbb{R}$. Scalars as elements of the set of real numbers $x \in \mathbb{R}$ with sum, multiplication, etc.
We define subset of numbers: natural numbers $\mathbb{N}$, integers $\mathbb{Z}$, rational numbers $\mathbb{Q}$ and irrational numbers $\mathbb{R}\setminus\mathbb{Q}$

In [66]:
m = 100. 
n = 5.0
type(m), type(n), type(m + n), m + n

(float, float, float, 105.0)

Take $a \in \mathbb{R}$ then for each $b \in \mathbb{R}$ there exists $\alpha \in \mathbb{R}$ such that $b = \alpha a$

## Vectors

vectors can be considered as subset of cartesian product of $\mathbb{R}$ ($\mathbb{N}$, $\mathbb{Z}$, $\mathbb{Q}$, etc)
<br>
For instance vector $x = (x_1, x_2, \dots, x_n)$ we can write $x \in \mathbb{R}^{n}$
<br>

In [68]:
import numpy as np

In [69]:
la = [1, 2, 3, 4]
na = np.array([1,2,3,4,5])
la, na

([1, 2, 3, 4], array([1, 2, 3, 4, 5]))

In many cases we'll work with collumn vectors like $\begin{align}
    x &= \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{m}
         \end{bmatrix}
  \end{align}$

What is the difference between set $\{a_1, a_2, \dots, a_n\}$ and vector $(a_1, a_2, \dots, a_n)$?

Indexing the vectors

In [70]:
la[-1], la[2], la[2:], la[:-1], la[2:4]

(4, 3, [3, 4], [1, 2, 3], [3, 4])

In [71]:
na[-1], na[2], na[2:], na[:-1], na[2:4]

(5, 3, array([3, 4, 5]), array([1, 2, 3, 4]), array([3, 4]))

In [72]:
lid = [1, 2]
na[lid]

array([2, 3])

In [73]:
nid = np.array(lid)

In [74]:
na[lid]

array([2, 3])

## Matrices

Matrix $X$ can be considered as mulitidimensional array 
$\begin{align}
    X &= \begin{matrix}
        x_{11} & x_{12} & \dots x_{1m} \\
        x_{21} & x_{22} & \dots x_{2m} \\
        \vdots & \vdots & \vdots \\
        x_{n1} & x_{n2} & \dots x_{nm} \\
    \end{matrix}
\end{align}$
or 
$\begin{align}
    X &= \begin{pmatrix}
        x_{11} & x_{12} & \dots x_{1m} \\
        x_{21} & x_{22} & \dots x_{2m} \\
        \vdots & \vdots & \vdots \\
        x_{n1} & x_{n2} & \dots x_{nm} \\
    \end{pmatrix}
\end{align}$
or
$\begin{align}
    X &= \begin{bmatrix}
        x_{11} & x_{12} & \dots x_{1m} \\
        x_{21} & x_{22} & \dots x_{2m} \\
        \vdots & \vdots & \vdots \\
        x_{n1} & x_{n2} & \dots x_{nm} \\
    \end{bmatrix}
\end{align}$
<br>
Matrix also can be defined by indices $A_{i, j}$ if we don't need concrete demensions

We say that $X$ has $n \times m$ dimension
<br>
or $X \in \mathbb{R}^{n \times m}$

e.g. $\begin{align}
    X &= \begin{pmatrix}
        1 & 2 & 3 \\
        4 & 5 & 6 \\
        7 & 8 & 9 \\
    \end{pmatrix}
\end{align}$
<br>
Then $X_{23} = 6$

Main diagonal of matrix $X$ are elements $x_{i,j}$ where $i = j$
<br>
$\begin{align}
    X &= \begin{pmatrix}
        x_{11} &  & \dots \\
         & x_{22} & \dots \\
        \vdots & \vdots & \vdots \\
         &  & \dots x_{nm} \\
    \end{pmatrix}
\end{align}$


In [75]:
lm = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
nm = np.array(lm) # np.array([[1, 2, 3], [4, 5, 6]])
print(lm)
print(nm)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
lm[1][2], nm[1][2]

(6, 6)

In [77]:
lm[1:], nm[1:]

([[4, 5, 6], [7, 8, 9]], array([[4, 5, 6],
        [7, 8, 9]]))

In [78]:
print(lm[1:2]) 
print(nm[1:, :]) 
nc_1 = nm[0, :]
print(nc_1)
nc_1[0] = 12
nm, nc_1

[[4, 5, 6]]
[[4 5 6]
 [7 8 9]]
[1 2 3]


(array([[12,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]), array([12,  2,  3]))

In [79]:
np.diag(nm, k=0)

array([12,  5,  9])

## Tensors

Let's go to the higher dimesions and define tensor $X$ as part of $R^{n \times m \times k}$
<br>
then we have a three indices instead of two, and $x_{i, j, k}$ is the element of tensor $X$ across the $i, j$ and $k$ indices

In similar manner we can define more than three dimensional tensors $X \in \mathbb{R}^{n_1 \times n_2 \times \dots \times n_p}$

In [80]:
lt = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
mt = np.array(lt) # or np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(mt)
print(lt)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]


In [81]:
mt = np.random.randint(0,100, size=(3, 3, 3))

In [82]:
mt

array([[[64, 30, 70],
        [ 6, 16, 27],
        [82, 92, 78]],

       [[52,  4, 94],
        [91, 52, 72],
        [51, 68,  7]],

       [[33, 20, 45],
        [70, 66, 44],
        [13, 36, 85]]])

In [84]:
md = np.random.randint(0,100, size=(2, 3, 4))

In [85]:
md

array([[[50, 55, 97, 27],
        [61, 17, 42, 98],
        [ 8,  3, 97, 33]],

       [[78,  1, 61, 52],
        [77, 87, 17, 70],
        [13, 23, 87, 49]]])

In [88]:
mmd = np.random.randint(0,100, size=(2, 3, 4, 5, 6))

In [89]:
mmd

array([[[[[12,  0, 79, 89, 48, 65],
          [80, 80, 71, 34, 26, 88],
          [87, 80, 68, 32, 23, 29],
          [13, 78, 12, 69, 23, 89],
          [ 6, 14, 95,  4,  3, 64]],

         [[46, 45, 61, 14, 58, 91],
          [42, 89, 37, 54, 38, 31],
          [31, 81,  2, 66, 12, 21],
          [53, 48, 60, 19,  9, 56],
          [71,  4,  3, 25, 77, 28]],

         [[77, 11, 36, 55, 64, 22],
          [ 5, 44, 95, 62, 69, 46],
          [96, 83, 69, 89, 97, 80],
          [39, 62, 40,  7, 18, 85],
          [94, 48, 75, 71, 50, 74]],

         [[44, 56, 18, 59, 16, 72],
          [90, 32, 18, 70, 41,  8],
          [59, 97, 44, 33, 21, 22],
          [16, 46, 32, 46, 68, 25],
          [80, 33, 80, 97, 29, 14]]],


        [[[20,  1,  4,  8, 51, 77],
          [50, 19, 40, 74, 88, 71],
          [47, 49, 99, 20, 90, 94],
          [94, 23, 71, 60, 30,  0],
          [65, 83, 71,  7, 22, 32]],

         [[63,  2, 76, 20, 57, 14],
          [24, 92, 84, 40, 59, 63],
          [46, 1

Transpose of matrix $X$ denoted by $X^T$ defined by elements $(X^{T})_{i, j} = X_{j, i}$ or $X \in \mathbb{R}^{n \times m}$ then $T^{T} \in \mathbb{R}^{m \times n}$
<br>
e.g.
<br>
$\begin{align}
    X &= \begin{pmatrix}
        x_{11} & x_{12} & \dots x_{1m} \\
        x_{21} & x_{22} & \dots x_{2m} \\
        \vdots & \vdots & \vdots \\
        x_{n1} & x_{n2} & \dots x_{nm} \\
    \end{pmatrix}
\end{align}$ then $\begin{align}
    X^{T} &= \begin{pmatrix}
        x_{11} & x_{21} & \dots x_{m1} \\
        x_{12} & x_{22} & \dots x_{m2} \\
        \vdots & \vdots & \vdots \\
        x_{1n} & x_{2n} & \dots x_{mn} \\
    \end{pmatrix}
\end{align}$

Transpose can be thought as mirror along with the main diagonal

Visualisation of transpose matrix $X \in \mathbb{R}^{4 \times 4}$

![SegmentLocal](images/la1/transpose1.gif "segment")

Transpose matrix $X \in \mathbb{R}^{2 \times 3}$

![SegmentLocal](images/la1/transpose2.gif "segment")

We can consider scalar as one dimensional vector and vector as $v = (v_1, v_2, \dots, v_n)$ as matrix with $1 \times n$ dimensions and 
$\begin{align}
    u &= \begin{bmatrix}
           u_{1} \\
           u_{2} \\
           \vdots \\
           u_{m}
         \end{bmatrix}
 \end{align}$ as matrix with $m \times 1$ dimensions
<br>
then 
$\begin{align}
    v^{T} &= \begin{bmatrix}
           v_{1} \\
           v_{2} \\
           \vdots \\
           v_{n}
         \end{bmatrix}
 \end{align}$ and $u^{T} = (u_1, u_2, \dots, u_m)$

In [90]:
print(nm)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [91]:
print(nm.T)

[[12  4  7]
 [ 2  5  8]
 [ 3  6  9]]


For scalar $a \in \mathbb{R}$ we have $a^{T} = a$

# Operations on Matrices

We can add two $A, B \in \mathbb{R}^{n \times m}$ matrices $C = A + B$ as 
$\begin{align}
    C &= \begin{pmatrix}
        {a_{11} + b_{11}} & {a_{12} + b_{12}} & \dots {a_{1m} + b_{1m}} \\
        {a_{21} + b_{21}} & {a_{22} + b_{22}} & \dots {a_{2m} + b_{2m}} \\
        \vdots & \vdots & \vdots \\
        {a_{n1} + b_{n1}} & {a_{n2} + b_{n2}} & \dots {a_{nm} + b_{nm}} \\
    \end{pmatrix}
\end{align}$ or we could write $c_{i, j} = a_{i, j} + b_{i, j}$

In [92]:
m1 = np.array([[2, 4, 6], [12, 14, 16], [22, 24, 26]])
m2 = np.array([[1, 3, 4], [11, 13, 14], [42, 44, 44]])
print(m1)
print(m2)
print(m1 + m2)

[[ 2  4  6]
 [12 14 16]
 [22 24 26]]
[[ 1  3  4]
 [11 13 14]
 [42 44 44]]
[[ 3  7 10]
 [23 27 30]
 [64 68 70]]


Add scalar $a \in \mathbb{R}$ and matrix $X \in \mathbb{R}^{n \times m}$ as 
$\begin{align}
    X + a &= \begin{pmatrix}
        {x_{11} + a} & {x_{12} + a} & \dots {x_{1m} + a} \\
        {x_{21} + a} & {x_{22} + a} & \dots {x_{2m} + a} \\
        \vdots & \vdots & \vdots \\
        {x_{n1} + a} & {x_{n2} + a} & \dots {x_{nm} + a} \\
    \end{pmatrix}
\end{align}$ or we could write ${(X + a)}_{i, j} = x_{i, j} + a$
<br>
In the same way we can define ${(a + X)}_{i, j} = a + x_{i, j}$
<br>
Multiplication of scalar and matrix
$\begin{align}
    Xa &= \begin{pmatrix}
        {x_{11}a} & {x_{12}a} & \dots {x_{1m}a} \\
        {x_{21}a} & {x_{22}a} & \dots {x_{2m}a} \\
        \vdots & \vdots & \vdots \\
        {x_{n1}a} & {x_{n2}a} & \dots {x_{nm}a} \\
    \end{pmatrix}
\end{align}$ or we could write ${(X + a)}_{i, j} = x_{i, j} + a$
<br>
In the same way we can define ${(aX)}_{i, j} = ax_{i, j}$
<br>
so we have $C = aX + b$ for $a \in \mathbb{R}$ and matrix $X \in \mathbb{R}^{n \times m}$


Prove that $a + X = X + a$ and $aX = Xa$ for every scalar $a \in \mathbb{R}$ and matrix $X \in \mathbb{R}^{n \times m}$

In [93]:
m1, m1*5 + 2

(array([[ 2,  4,  6],
        [12, 14, 16],
        [22, 24, 26]]), array([[ 12,  22,  32],
        [ 62,  72,  82],
        [112, 122, 132]]))

Add matrix and vector $A + b$ where $A \in \mathbb{R}^{n \times m}$ $b \in \mathbb{R}^{1 \times m}$ can be done by broadcasting
<br>
$C_{i, j} = A_{i, j} + b_{j}$

In [94]:
v1 = np.array([[2], [4], [6]])


In [95]:
print(m1)
print(v1)
print(v1.T)
print(m1 + v1)
print(m1 + v1.T)

[[ 2  4  6]
 [12 14 16]
 [22 24 26]]
[[2]
 [4]
 [6]]
[[2 4 6]]
[[ 4  6  8]
 [16 18 20]
 [28 30 32]]
[[ 4  8 12]
 [14 18 22]
 [24 28 32]]


For matrix $A \in \mathbb{R}^{n \times m}$ and $B \in \mathbb{R}^{m \times l}$ let's define $C = AB$ as $C_{i, j} = \sum_{k = 1}^{n}{A_{i, k}B_{k, j}}$ it is clear that $C \in \mathbb{R}^{n \times l}$

Lets visualize

![SegmentLocal](images/la1/mult1.gif "segment")

In [96]:
m1 = np.array([[1, 2, 1], [0, 1, 0], [2, 3, 4]])
m2 = np.array([[2, 5], [6, 7], [1, 8]])

In [97]:
print(m1)
print(m2)

[[1 2 1]
 [0 1 0]
 [2 3 4]]
[[2 5]
 [6 7]
 [1 8]]


In [98]:
m3 = m1 @ m2

In [99]:
print(m3)

[[15 27]
 [ 6  7]
 [26 63]]


Or slower version

![SegmentLocal](images/la1/mult2.gif "segment")

In [100]:
n1 = np.array([[8, 1, 2], [-5, 6, 7]])
n2 = np.array([[-5, 1], [0, 2], [-11, 7]])

In [101]:
print(n1)
print(n2)

[[ 8  1  2]
 [-5  6  7]]
[[ -5   1]
 [  0   2]
 [-11   7]]


In [102]:
n3 = np.dot(n1, n2)

In [103]:
print(n3) #, n3

[[-62  24]
 [-52  56]]


Hadamard product of $A \in \mathbb{R^{n \times m}}$ and $B \in \mathbb{R^{n \times m}}$ define $C = A \odot B$ if $C_{i, j} = A_{i, j}B_{i, j}$ (elementwise product)

In [104]:
a1 = np.random.random(size=(2, 3))
a2 = np.random.random(size=(2, 3))

In [105]:
print(a1)

print(a2)

print(a1 * a2)

[[0.97438359 0.38582415 0.73489182]
 [0.50256481 0.11059785 0.0256423 ]]
[[0.45528183 0.83716544 0.23269749]
 [0.51778272 0.22749834 0.08628343]]
[[0.44361915 0.32299864 0.17100748]
 [0.26021937 0.02516083 0.00221251]]


In [106]:
a1 = np.array([[1, 2], [4, 8], [3., 4.]])
a2 = np.array([[2, 4.], [4., 4], [3., 2.]])

In [107]:
a1

array([[1., 2.],
       [4., 8.],
       [3., 4.]])

In [108]:
a2

array([[2., 4.],
       [4., 4.],
       [3., 2.]])

In [109]:
a1 * a2

array([[ 2.,  8.],
       [16., 32.],
       [ 9.,  8.]])

In [110]:
np.sum(a1 * a2)

75.0

In [111]:
np.multiply(a1, a2)

array([[ 2.,  8.],
       [16., 32.],
       [ 9.,  8.]])

In [112]:
np.sum(np.multiply(a1, a2))

75.0

In [113]:
a1 = np.arange(3*2).reshape((3, 2))
a1 = np.arange(3*2).reshape((2, 3))

In [114]:
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
a2

array([[2., 4.],
       [4., 4.],
       [3., 2.]])

In [116]:
a1 @ a2

array([[10.,  8.],
       [37., 38.]])

Dot product of vectors $v, u \in \mathbb{R}^{n}$ define as $v^{T}u$

Prove that $v^{T}u = vu^{T}$ for each $v, u \in \mathbb{R}^{n}$

For each pair of matrices $A, B \in \mathbb{R}^{n \times m}$ holds:
- $A + B = B + A$
- $A(B + C) = AB + AC$
- $A(BC) = (AB)C$

Prove that $(AB)^{T} = B^{T}A^{T}$ for each pair of matrices $A, B \in \mathbb{R}^{n \times m}$

$(AB)_{ij} = \sum_{k=1}^n a_{ik} b_{kj}$

$[(AB)_{ij}]^T = \sum_{k=1}^n a_{jk}b_{ki}

For instance $Ax=b$

Vectorization vs loops

In [ ]:
l1 = np.random.randn(3, 4)
l2 = np.random.randn(4, 6)
l1, l2

In [ ]:
def dot_prod(mx1, mx2, verbose = False):
    mx3 = np.zeros((mx1.shape[0], mx2.shape[1]))
    if verbose: print(f'mx3.shape = {mx3.shape}')
    for i in range(mx1.shape[0]):
        if verbose: print(f'i = {i}')
        for k in range(mx2.shape[1]):
            if verbose: print(f'\tk = {k}')
            for j in range(mx1.shape[1]):
                if verbose: print(f'\t\tj = {j}')
                s = mx1[i, j] + mx2[j, k]
            mx3[i, k] = s
    
    return mx3
            

In [ ]:
%time l3_loop = dot_prod(l1, l2)

In [ ]:
l3_loop

In [ ]:
l1 @ l2

In [ ]:
b1 = np.random.randn(500, 10000)
b2 = np.random.randn(10000, 800)
b1, b2

In [ ]:
%time b3_loop = dot_prod(b1, b2)

In [ ]:
def dot_prod_2(mx1, mx2, verbose = False):
    mx3 = np.zeros((mx1.shape[0], mx2.shape[1]))
    if verbose: print(f'mx3.shape = {mx3.shape}')
    for i in range(mx1.shape[0]):
        if verbose: print(f'i = {i}')
        for k in range(mx2.shape[1]):
            mx3[i, k] = np.dot(mx1[i, :], mx2[:, k])
            if verbose: 
                print(f'\tk = {mx1[i:]}') 
                print(f'\tk = {mx2[:, k]}')
            
            #mx3[i, k] = s
    
    return mx3

In [ ]:
%time l3_loop = dot_prod_2(l1, l2)

In [ ]:
l3_loop

In [ ]:
%time b3_loop = dot_prod_2(b1, b2)

Matrix vector multiplication

In [ ]:
def dot_prod_3(mx1, mx2, verbose = False):
    mx3 = np.zeros((mx1.shape[0], mx2.shape[1]))
    if verbose: print(f'mx3.shape = {mx3.shape}')
    for i in range(mx1.shape[0]):
        if verbose: print(f'i = {i}')
        mx3[i, :] = np.dot(mx1[i, :], mx2)
        if verbose: 
            print(f'\tk = {mx2[:, k]}')
            
            #mx3[i, k] = s
    
    return mx3

In [ ]:
%time l3_loop = dot_prod_3(l1, l2)

In [ ]:
l3_loop

In [ ]:
%time b3_loop = dot_prod_3(b1, b2)

## Vectorize version

In [ ]:
%time l3_vec = np.dot(l1, l2)

In [ ]:
l3_vec

In [ ]:
%time b3_vec = b1 @ b2

In [ ]:
b3_vec

In [ ]:
%time l3 = np.dot(l1, l2)

In [ ]:
%time b3 = np.dot(b1, b2)

In [ ]:
%time b3_vec = np.dot(b1, b2)

## Functions on tensors

We can define function $f:A \to B$ where $A, B \in \mathbb{R}^{n1 \times n2 \dots \times n_{k}}$ where function is defined elementwise $B_{i, j} = f(A_{i, j})$

For instance function $f(x) = x + 5$ on matrix $A \in \mathbb{R}^{n \times m}$ will give us $A + 5$

In [ ]:
mt = np.array([[1, 2], [-1, -2], [0., 4.]])
f = lambda x: x + 5
print(mt) 
print(f(mt))
print(mt + 5)

In [ ]:
import math

In [ ]:
f = lambda x: x**2

In [ ]:
f(-1)

In [ ]:
x = np.linspace(-5, 5, 1000)

In [ ]:
x

In [ ]:
fv = f #np.vectorize(f)

In [ ]:
fx = fv(x)

In [ ]:
x.shape, fx.shape

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(x, fx)

In [ ]:
sig = np.vectorize(lambda x: 1 / (1 + math.exp(-x)))

In [ ]:
plt.plot(x, sig(x))

In [ ]:
plt.plot(x, sig(x))
plt.grid()

## Images as tensors and matrices

In [ ]:
import cv2

In [ ]:
! pip install opencv-python

In [ ]:
from pathlib import Path

In [ ]:
path = Path('images')

In [ ]:
ls = ! ls {path}
la1 = path / ls[0]

In [ ]:
ls

In [ ]:
img_brg = cv2.imread(str(la1 / 'tbilisi1.jpg'), cv2.IMREAD_ANYCOLOR)

In [ ]:
type(img_brg), img_brg.shape

In [ ]:
plt.figure(figsize=(50, 50))
plt.imshow(img_brg, cmap=None)
plt.show()

In [ ]:
img = cv2.cvtColor(img_brg, cv2.COLOR_RGB2BGR)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
def show_img(im, figsize=(50, 50), cmap=None):
    plt.figure(figsize=figsize)
    plt.imshow(im, cmap=cmap)
    plt.show()

In [ ]:
show_img(img)

In [ ]:
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

In [ ]:
show_img(gray, cmap='gray')

In [ ]:
gray_t = gray.T

In [ ]:
gray_t.shape
show_img(gray_t, cmap='gray')

In [ ]:
show_img(gray - 100, cmap='gray')

## Example 1

In [ ]:
X = np.random.rand(10)
A = np.random.rand(10)
b = np.random.rand(1)

In [ ]:
A @ X + b

In [ ]:
sig(A @ X + b)

## Example 2

In [ ]:
W = np.array([20, 20]) # Weights
b = np.array([-30]) # bias

In [ ]:
X = np.array([1, 0])

In [ ]:
d = sig(W2 @ sig(W1.T @ X1 + b1) + b2)

In [ ]:
np.around(d, decimals=1)

In [ ]:
ff = lambda _X, _W, _b: sig(np.dot(_W.T, _X) + _b)

In [ ]:
BA = [[0, 0], [0, 1], [1, 0], [1, 1]]

In [ ]:
for ba in BA:
    print(ba, np.around(ff(ba, W, b), decimals=1))

Change bias

In [ ]:
b = np.array([-10])

In [ ]:
for ba in BA:
    print(ba, np.around(ff(ba, W, b), decimals=1))

Write combination for $XOR$ calculation